name: GitHub Pages Deploy

# Ensure the following 4 items are defined/updated:
#   1. runner env GA_TRACKING_ID: Google Analytics tracking ID
#   2. runner env PERSONAL_ACCESS_TOKEN: GitHub Personal Access Token with rights to the repo.

#   3. Update source branch and other trigger filters.
on:
  push:
    branches:
      - dev
    paths:
      - "**"
      - "!README.md"
      - "!CHANGELOG.md"

#   4. Update destination branch and artifact folder source.
env:
  DEST_BRANCH: "master"
  ARTIFACT_DIR: "public"

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Build ${{ github.ref }}
        env:
#          URL_RECENT_DECK: ${{ secrets.URL_RECENT_DECK }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        run: |
          npm install
          npm run build

      - name: Check-out '${{ env.DEST_BRANCH }}' to 'temp'
        run: |
          git clone -b ${{ env.DEST_BRANCH }} --single-branch http://github.com/${{ github.repository }}.git temp

      - name: Clean '${{ env.DEST_BRANCH }}' at 'temp'
        run: |
          rm -rf temp/*
          rm -rf temp/.github/
          echo '.git' folder retained at 'temp'

      - name: Transfer '${{ env.ARTIFACT_DIR }}' contents to 'temp'
        run: |
          cp -r ${{ env.ARTIFACT_DIR }}/. temp/

      - name: Commit new artifacts to cleaned '${{ env.DEST_BRANCH }}'
        working-directory: ./temp
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@bots.github.com"
          git add .
          git commit -m "updating from ${{ github.sha }}"

      - name: Soft force-push new artifacts to '${{ env.DEST_BRANCH }}' for GitHub Pages rendering
        working-directory: ./temp
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git" # includes access token
          git push --force-with-lease
